# Generated by Django 4.0.6 on 2022-10-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='placeholder', max_length=128)),
                ('name', models.CharField(default='placeholder', max_length=20)),
                ('affiliation', models.CharField(default='placeholder', max_length=40)),
                ('position', models.CharField(default='placeholder', max_length=20)),
                ('standing', models.CharField(default='placeholder', max_length=20)),
                ('registered_id', models.CharField(max_length=150, null=True, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=10)),
                ('uploader', models.CharField(max_length=10)),
                ('associate', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('collected', models.IntegerField(default=0)),
                ('private', models.IntegerField(default=0)),
                ('attendee', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('src', models.ImageField(upload_to='image/%Y%m%d')),
            ],
        ),
    ]
