# Generated by Django 3.2.14 on 2022-11-04 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='affiliation',
        ),
    ]
