# Generated by Django 4.0.6 on 2022-10-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocase',
            name='form',
            field=models.IntegerField(default=1),
        ),
    ]
