# Generated by Django 4.0.6 on 2022-10-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=10)),
                ('uploader', models.CharField(max_length=10)),
                ('associate', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('collected', models.IntegerField(default=0)),
                ('private', models.IntegerField(default=0)),
                ('attendee', models.JSONField(blank=True, verbose_name=models.CharField(max_length=20))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('src', models.ImageField(upload_to='image/%Y%m%d')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/%Y%m%d'),
        ),
    ]
