# Generated by Django 4.0.6 on 2022-10-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0002_case_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='attendee',
            field=models.JSONField(),
        ),
    ]
