# Generated by Django 4.1.2 on 2022-11-10 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0002_remove_user_affiliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=300)),
                ('request_form', models.IntegerField(default=1)),
                ('auth_from', models.IntegerField()),
                ('auth_to', models.IntegerField()),
                ('status', models.IntegerField(default=2)),
                ('request_form1_requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_form1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessRequestComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_case_form', models.IntegerField()),
                ('status', models.IntegerField()),
                ('doc_cases', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requested', to='sample_backend.doccase')),
                ('image_cases', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requested', to='sample_backend.imagecase')),
                ('video_cases', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requested', to='sample_backend.videocase')),
            ],
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=300)),
                ('request_form', models.IntegerField(default=0)),
                ('request_components', models.ManyToManyField(related_name='requested_in', to='sample_backend.accessrequestcomponent')),
                ('request_form0_requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_form0', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
