# Generated by Django 4.0.6 on 2022-10-24 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0002_videocase_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocase',
            name='form1_accessed_by',
            field=models.ManyToManyField(related_name='access_to_form1', to=settings.AUTH_USER_MODEL),
        ),
    ]
