# Generated by Django 4.0.6 on 2022-10-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0003_videocase_form1_accessed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocase',
            name='form',
        ),
    ]
