# Generated by Django 4.1.2 on 2022-11-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0003_authorityrequest_accessrequestcomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='status',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='accessrequestcomponent',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
