# Generated by Django 4.0.6 on 2022-10-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0003_alter_case_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='attendee',
            field=models.CharField(max_length=20),
        ),
    ]
