# Generated by Django 4.0.6 on 2022-10-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0004_alter_case_attendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default="placeholder", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default="placeholder", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='registered_id',
            field=models.CharField(default=None, max_length=150, unique=True, null = True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='standing',
            field=models.CharField(null = True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(null = True, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='affiliation',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
