# Generated by Django 4.1.2 on 2022-11-11 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0004_accessrequest_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrequestcomponent',
            old_name='doc_cases',
            new_name='doc_case',
        ),
        migrations.RenameField(
            model_name='accessrequestcomponent',
            old_name='image_cases',
            new_name='image_case',
        ),
        migrations.RenameField(
            model_name='accessrequestcomponent',
            old_name='video_cases',
            new_name='video_case',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='status',
        ),
    ]
