# Generated by Django 4.0.6 on 2022-10-24 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0005_videocase_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='doccase',
            name='form',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='doccase',
            name='form2_accessed_by',
            field=models.ManyToManyField(related_name='access_to_form2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagecase',
            name='form',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagecase',
            name='form0_accessed_by',
            field=models.ManyToManyField(related_name='access_to_form0', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='form',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='location',
            name='form4_accessed_by',
            field=models.ManyToManyField(related_name='access_to_form4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personel',
            name='form',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='personel',
            name='form3_accessed_by',
            field=models.ManyToManyField(related_name='access_to_form3', to=settings.AUTH_USER_MODEL),
        ),
    ]
