# Generated by Django 4.1.2 on 2022-11-14 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0005_rename_doc_cases_accessrequestcomponent_doc_case_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('hidden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('message_type', models.IntegerField()),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
