# Generated by Django 4.1.2 on 2022-11-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
