# Generated by Django 4.1 on 2022-12-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_backend", "0007_accessrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="doccase", name="uploaded", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imagecase",
            name="uploaded",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="location",
            name="uploaded",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="personel",
            name="uploaded",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="videocase",
            name="uploaded",
            field=models.IntegerField(default=0),
        ),
    ]
