# Generated by Django 4.1 on 2022-12-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_backend", "0008_doccase_uploaded_imagecase_uploaded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="affiliation",
            field=models.CharField(default="없음", max_length=100),
        ),
    ]
