# Generated by Django 4.1.2 on 2022-12-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0009_user_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
