# Generated by Django 4.0.6 on 2022-10-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='affiliation',
            field=models.CharField(default='placeholder', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='placeholder', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(default='placeholder', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='standing',
            field=models.CharField(default='placeholder', max_length=20),
        ),
    ]
