# Generated by Django 4.0.6 on 2022-10-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0011_alter_user_affiliation_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered_id',
            field=models.CharField(default='placeholder', max_length=150, unique=True),
        ),
    ]
