# Generated by Django 4.0.6 on 2022-10-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0012_alter_user_registered_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered_id',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
