# Generated by Django 4.0.6 on 2022-10-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0013_alter_user_registered_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registered_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='affiliation',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='standing',
            field=models.CharField(max_length=20),
        ),
    ]
