# Generated by Django 4.0.6 on 2022-10-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0014_remove_user_registered_id_alter_user_affiliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='2022-10-16 11:21:02.356562+00:00', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
