# Generated by Django 3.2.14 on 2022-10-18 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0016_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('private', models.IntegerField()),
                ('form', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('private', models.IntegerField()),
                ('produced', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('private', models.IntegerField()),
                ('construction_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('private', models.IntegerField()),
                ('birth_date', models.DateTimeField()),
                ('prefix', models.CharField(max_length=20)),
                ('affiliation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample_backend.location')),
                ('connected_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample_backend.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('private', models.IntegerField()),
                ('produced', models.IntegerField()),
                ('affiliation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_affiliation_in_form1', to='sample_backend.location')),
                ('associate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample_backend.user')),
                ('attendee', models.ManyToManyField(related_name='appears_in_form1', to='sample_backend.Personel')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_location_in_form1', to='sample_backend.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('name', models.CharField(max_length=300)),
                ('extension', models.CharField(max_length=20)),
                ('url', models.FileField(upload_to='stream/video/%Y%m%d')),
                ('image_of', models.ManyToManyField(related_name='view', to='sample_backend.Location')),
                ('profile_of', models.ManyToManyField(related_name='profile', to='sample_backend.Personel')),
                ('referenced_in', models.ManyToManyField(related_name='include', to='sample_backend.VideoCase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('name', models.CharField(max_length=300)),
                ('extension', models.CharField(max_length=20)),
                ('url', models.ImageField(upload_to='stream/image/%Y%m%d')),
                ('referenced_in', models.ManyToManyField(related_name='include', to='sample_backend.ImageCase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='imagecase',
            name='affiliation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_affiliation_in_form0', to='sample_backend.location'),
        ),
        migrations.AddField(
            model_name='imagecase',
            name='associate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample_backend.user'),
        ),
        migrations.AddField(
            model_name='imagecase',
            name='attendee',
            field=models.ManyToManyField(related_name='appears_in_form0', to='sample_backend.Personel'),
        ),
        migrations.AddField(
            model_name='imagecase',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_location_in_form0', to='sample_backend.location'),
        ),
        migrations.CreateModel(
            name='DocMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('name', models.CharField(max_length=300)),
                ('extension', models.CharField(max_length=20)),
                ('url', models.FileField(upload_to='stream/document/%Y%m%d')),
                ('referenced_in', models.ManyToManyField(related_name='include', to='sample_backend.DocCase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doccase',
            name='referenced_personel',
            field=models.ManyToManyField(related_name='referenced_in', to='sample_backend.Personel'),
        ),
        migrations.AddField(
            model_name='doccase',
            name='writer',
            field=models.ManyToManyField(related_name='wrote', to='sample_backend.Personel'),
        ),
    ]
