# Generated by Django 3.2.14 on 2022-10-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0017_auto_20221018_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecase',
            name='form',
        ),
        migrations.RemoveField(
            model_name='location',
            name='form',
        ),
        migrations.RemoveField(
            model_name='personel',
            name='form',
        ),
        migrations.RemoveField(
            model_name='videocase',
            name='form',
        ),
    ]
