# Generated by Django 3.2.14 on 2022-10-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_backend', '0018_auto_20221018_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doccase',
            name='form',
        ),
    ]
